### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by matks** [pplotka/local-php-security-checker-github-actions#3]
Hi,

If you do not select a license for this repository, [according to GitHub](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository),

"the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work."

Would you please choose a license for this project, so it clears what can be done and what cannot 😊  ?

**Comment by pplotka** [comment]
Thank you for your suggestion and sorry for the late response (GitHub didn't send me a notification about your issue). 

I decided to distribute this project under AGPL-3.0 License (the same as Local Security Checker).
